database:
  host: sqlserver.database.windows.net
  username: myusername
  password: mypassword
image:
  repository: myapp
  tag: latest
  pullPolicy: Always
  

# PostSync Hook in ArgoCD that runs helm upgrade command + imagePullPolicy: Always in helm chart
# This provides every time a new image is pushed to the registry, helm will pull it and argocd will deploy it

# General Ideas:
# ArgoCD Container Registry'den triggerlanabilir mi?
# Helm Chart Container Registry'den triggerlanabilir mi?  
# Add something at the end of the workflow to make a request to the argo endpoint

