apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-upgrade-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: upgrade-helm
          image: alpine/helm:3.11.1 
          command:
            - "/bin/sh"
            - "-c"
            - "helm upgrade --install my-release ./helm"
      restartPolicy: Never
  backoffLimit: 2
